# Generated by Django 3.2 on 2022-06-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='approvedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='expireDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='approvedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='expireDate',
            field=models.DateTimeField(null=True),
        ),
    ]
