# Generated by Django 3.2 on 2022-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_auto_20220617_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
