# Generated by Django 3.2 on 2022-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_auto_20220620_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resell',
            name='price',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
