# Generated by Django 3.2 on 2022-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_alter_resell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
