# Generated by Django 3.2.9 on 2021-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
