# Generated by Django 3.2 on 2022-10-08 01:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_auto_20221007_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='metadesc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='metadesc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='metadesc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
