# Generated by Django 3.2.9 on 2021-12-24 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productivity', '0009_auto_20211205_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, default='image', max_length=300)),
                ('title', models.TextField(blank=True, default='title', null=True)),
                ('content', models.TextField(blank=True, default='content', null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('isApproved', models.BooleanField(default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.shops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
