# Generated by Django 3.2 on 2022-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0012_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
