# Generated by Django 3.2 on 2022-01-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0014_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownbusiness',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resell',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourisms',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
