# Generated by Django 3.2 on 2022-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0015_auto_20220113_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
