# Generated by Django 3.2 on 2022-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0019_tourisms_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
