# Generated by Django 3.2 on 2022-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0020_auto_20220123_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrities',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
