# Generated by Django 3.2 on 2022-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0021_celebrities_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='celebrities',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tourisms',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
