# Generated by Django 3.2 on 2022-04-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0022_auto_20220407_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
