# Generated by Django 3.2 on 2022-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0024_auto_20220426_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='images/advertisePlaceholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, default='./images/jopPlaceholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tourisms',
            name='image',
            field=models.ImageField(blank=True, default='/tourismsPlaceholder.jpg', upload_to=''),
        ),
    ]
