# Generated by Django 3.2 on 2022-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0025_auto_20220426_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, default='/jopPlaceholder.png', upload_to=''),
        ),
    ]
