# Generated by Django 3.2 on 2022-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0028_alter_jobs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, default='../images/jopPlaceholder.jpg', upload_to=''),
        ),
    ]
