# Generated by Django 3.2 on 2022-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0031_alter_jobs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='advertisePlaceholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, default='jopPlaceholder.jpg', upload_to=''),
        ),
    ]
