# Generated by Django 3.2 on 2022-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0032_auto_20220426_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourisms',
            name='fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
