# Generated by Django 3.2 on 2022-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0033_tourisms_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourisms',
            name='content',
            field=models.TextField(blank=True, default='Best Tourisms spot', null=True),
        ),
        migrations.AlterField(
            model_name='tourisms',
            name='title',
            field=models.TextField(blank=True, default='Best Tourisms Spot', null=True),
        ),
    ]
