# Generated by Django 3.2 on 2022-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0034_auto_20220426_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourisms',
            name='contact',
            field=models.CharField(blank=True, default='91+ 000000xxxxx', max_length=100, null=True),
        ),
    ]
