# Generated by Django 3.2 on 2022-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0035_alter_tourisms_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourisms',
            name='hotel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tourisms',
            name='resort',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
