# Generated by Django 3.2 on 2022-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0036_auto_20220426_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrities',
            name='image',
            field=models.ImageField(blank=True, default='celebrityPlaceholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shops',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tourisms',
            name='image',
            field=models.ImageField(blank=True, default='tourismsPlaceholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tourismsgallary',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', upload_to='tourismsImage'),
        ),
    ]
