# Generated by Django 3.2 on 2022-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0038_auto_20220429_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, default='jopPlaceholder.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tourisms',
            name='image',
            field=models.ImageField(blank=True, default='tourismsPlaceholder.jpg', upload_to=''),
        ),
    ]
