# Generated by Django 3.2 on 2022-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0039_auto_20220429_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourisms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
