# Generated by Django 3.2 on 2022-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0040_alter_tourisms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourisms',
            name='image',
            field=models.ImageField(blank=True, default='tourismsPlaceholder.jpg', null=True, upload_to=''),
        ),
    ]
