# Generated by Django 3.2 on 2022-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0041_alter_tourisms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
