# Generated by Django 3.2 on 2022-05-03 03:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0044_auto_20220502_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', tinymce.models.HTMLField(blank=True, null=True)),
                ('qualification', tinymce.models.HTMLField(blank=True, null=True)),
                ('experience', tinymce.models.HTMLField(blank=True, null=True)),
                ('howToApply', tinymce.models.HTMLField(blank=True, null=True)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.jobs')),
            ],
        ),
    ]
