# Generated by Django 3.2 on 2022-05-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0045_jobdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDetail',
            new_name='JobsDetail',
        ),
    ]
