# Generated by Django 3.2 on 2022-06-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboards', '0004_alter_useraccount_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=220, null=True)),
                ('message', models.CharField(blank=True, max_length=220, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
