# Generated by Django 3.2 on 2022-06-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboards', '0006_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Contact us', 'verbose_name_plural': 'Contact us'},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
