# Generated by Django 3.2 on 2022-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0002_auto_20220624_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='localnews',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
