# Generated by Django 3.2 on 2022-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0003_auto_20220626_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localnews',
            name='description',
        ),
        migrations.AlterField(
            model_name='localnews',
            name='category',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('TECHNOLOGY', 'Technology'), ('ENVIRONMENT', 'Environment'), ('SCIENCE', 'Science'), ('POLITICS', 'Politics'), ('JOBS', 'Jobs'), ('Skill', 'Skill')], default='EDUCATION', max_length=200, null=True),
        ),
    ]
