# Generated by Django 3.2 on 2022-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0004_auto_20220729_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='category',
            field=models.CharField(blank=True, choices=[('education', 'education'), ('technology', 'technology'), ('environment', 'environment'), ('science', 'science'), ('politics', 'politics'), ('jobs', 'jobs'), ('skill', 'skill')], default='EDUCATION', max_length=200, null=True),
        ),
    ]
