# Generated by Django 3.2.9 on 2021-12-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_api_app', '0005_localnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='username', max_length=300, null=True)),
                ('firstName', models.CharField(blank=True, default='First Name', max_length=300, null=True)),
                ('lastName', models.CharField(blank=True, default='Last Name', max_length=300, null=True)),
                ('state', models.CharField(blank=True, default='State', max_length=300, null=True)),
                ('town', models.CharField(blank=True, default='town', max_length=300, null=True)),
                ('country', models.CharField(blank=True, default='country', max_length=300, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
