# Generated by Django 3.2 on 2022-10-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0006_auto_20221007_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='localnews',
            name='metadesc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='metadesc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
