# Generated by Django 3.2.9 on 2021-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0007_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='Profession', max_length=300, null=True),
        ),
    ]
