# Generated by Django 3.2.9 on 2021-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0008_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
