# Generated by Django 3.2.9 on 2021-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0009_profile_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
