# Generated by Django 3.2.9 on 2021-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0010_profile_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='localnews',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
