# Generated by Django 3.2.9 on 2021-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0013_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='url',
            field=models.CharField(blank=True, default='Url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='url',
            field=models.CharField(blank=True, default='Url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='localnews',
            name='url',
            field=models.CharField(blank=True, default='Url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='url',
            field=models.CharField(blank=True, default='Url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='url',
            field=models.CharField(blank=True, default='Url', max_length=500, null=True),
        ),
    ]
