# Generated by Django 3.2.9 on 2021-12-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0014_auto_20211208_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedAdvertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedCelebrities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedHotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedJob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedResseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedShop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isApprovedTourisms',
            field=models.BooleanField(default=False),
        ),
    ]
