# Generated by Django 3.2 on 2022-01-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0015_auto_20211224_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='localnews',
            name='image',
            field=models.ImageField(blank=True, default='/image.png', null=True, upload_to=''),
        ),
    ]
