# Generated by Django 3.2 on 2022-01-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0016_localnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='image',
            field=models.ImageField(blank=True, default='/image.png', upload_to=''),
        ),
    ]
