# Generated by Django 3.2 on 2022-01-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0017_alter_localnews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='localnews',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
    ]
