# Generated by Django 3.2 on 2022-01-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0018_auto_20220107_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localnews',
            name='urlToImage',
        ),
    ]
