# Generated by Django 3.2 on 2022-01-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0019_remove_localnews_urltoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isApprovedMeme',
            field=models.BooleanField(default=False),
        ),
    ]
