# Generated by Django 3.2 on 2022-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0021_requestform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
