# Generated by Django 3.2 on 2022-01-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0023_auto_20220110_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isRequested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
