# Generated by Django 3.2 on 2022-01-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0024_auto_20220113_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalNewsGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/placeholder.png', upload_to='localnewsImage')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api_app.localnews')),
            ],
        ),
    ]
