# Generated by Django 3.2 on 2022-01-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0025_localnewsgallary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localnews',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
