# Generated by Django 3.2 on 2022-04-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0026_rename_createat_localnews_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='localnews',
            name='flag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
