# Generated by Django 3.2 on 2022-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0027_localnews_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='image',
            field=models.ImageField(blank=True, default='/images/localnewsImage/newsPlaceholder.png', upload_to=''),
        ),
    ]
