# Generated by Django 3.2 on 2022-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0030_alter_localnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
