# Generated by Django 3.2 on 2022-05-02 15:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0031_alter_localnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
