# Generated by Django 3.2 on 2022-05-02 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0032_alter_technology_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
