# Generated by Django 3.2 on 2022-05-02 15:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0033_alter_localnews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localnews',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
