export const ADVERTISE_LIST_REQUEST = 'ADVERTISE_LIST_REQUEST';
export const ADVERTISE_LIST_SUCCESS = 'ADVERTISE_LIST_SUCCESS';
export const ADVERTISE_LIST_FAIL = 'ADVERTISE_LIST_FAIL'


export const ALL_ADVERTISE_LIST_REQUEST = 'ALL_ADVERTISE_LIST_REQUEST';
export const ALL_ADVERTISE_LIST_SUCCESS = 'ALL_ADVERTISE_LIST_SUCCESS';
export const ALL_ADVERTISE_LIST_FAIL =    'ALL_ADVERTISE_LIST_FAIL'


export const ADVERTISE_DETAIL_REQUEST = 'ADVERTISE_DETAIL_REQUEST';
export const ADVERTISE_DETAIL_SUCCESS = 'ADVERTISE_DETAIL_SUCCESS';
export const ADVERTISE_DETAIL_FAIL = 'ADVERTISE_DETAIL_FAIL'


export const ADVERTISE_CREATE_REQUEST = 'ADVERTISE_CREATE_REQUEST';
export const ADVERTISE_CREATE_SUCCESS = 'ADVERTISE_CREATE_SUCCESS';
export const ADVERTISE_CREATE_FAIL = 'ADVERTISE_CREATE_FAIL'
export const ADVERTISE_CREATE_RESET = 'ADVERTISE_CREATE_RESET'


export const ADVERTISE_UPDATE_REQUEST = 'ADVERTISE_UPDATE_REQUEST';
export const ADVERTISE_UPDATE_SUCCESS = 'ADVERTISE_UPDATE_SUCCESS';
export const ADVERTISE_UPDATE_FAIL = 'ADVERTISE_UPDATE_FAIL'
export const ADVERTISE_UPDATE_RESET = 'ADVERTISE_UPDATE_RESET'


export const ADVERTISE_DELETE_REQUEST = 'ADVERTISE_DELETE_REQUEST';
export const ADVERTISE_DELETE_SUCCESS = 'ADVERTISE_DELETE_SUCCESS';
export const ADVERTISE_DELETE_FAIL = 'ADVERTISE_DELETE_FAIL'
export const ADVERTISE_DELETE_RESET = 'ADVERTISE_DELETE_RESET'

export const ADVERTISE_USER_LIST_REQUEST = 'ADVERTISE_USER_LIST_REQUEST';
export const ADVERTISE_USER_LIST_SUCCESS = 'ADVERTISE_USER_LIST_SUCCESS';
export const ADVERTISE_USER_LIST_FAIL =    'ADVERTISE_USER_LIST_FAIL'


// CELEB CONSTANT
export const CELEBRITY_LIST_REQUEST = 'CELEBRITY_LIST_REQUEST';
export const CELEBRITY_LIST_SUCCESS = 'CELEBRITY_LIST_SUCCESS';
export const CELEBRITY_LIST_FAIL = 'CELEBRITY_LIST_FAIL'

export const CELEBRITY_USER_LIST_REQUEST = 'CELEBRITY_USER_LIST_REQUEST';
export const CELEBRITY_USER_LIST_SUCCESS = 'CELEBRITY_USER_LIST_SUCCESS';
export const CELEBRITY_USER_LIST_FAIL =    'CELEBRITY_USER_LIST_FAIL'


export const CELEBRITY_DETAIL_REQUEST = 'CELEBRITY_DETAIL_REQUEST';
export const CELEBRITY_DETAIL_SUCCESS = 'CELEBRITY_DETAIL_SUCCESS';
export const CELEBRITY_DETAIL_FAIL = 'CELEBRITY_DETAIL_FAIL'
export const  CELEBRITY_DETAIL_RESET = 'CELEBRITY_DETAIL_RESET'

export const CELEBRITY_CREATE_REQUEST = 'CELEBRITY_CREATE_REQUEST';
export const CELEBRITY_CREATE_SUCCESS = 'CELEBRITY_CREATE_SUCCESS';
export const CELEBRITY_CREATE_FAIL    = 'CELEBRITY_CREATE_FAIL'
export const CELEBRITY_CREATE_RESET   = 'CELEBRITY_CREATE_RESET'


export const CELEBRITY_UPDATE_REQUEST = 'CELEBRITY_UPDATE_REQUEST';
export const CELEBRITY_UPDATE_SUCCESS = 'CELEBRITY_UPDATE_SUCCESS';
export const CELEBRITY_UPDATE_FAIL    = 'CELEBRITY_UPDATE_FAIL'
export const CELEBRITY_UPDATE_RESET   = 'CELEBRITY_UPDATE_RESET'


export const CELEBRITY_DELETE_REQUEST = 'CELEBRITY_DELETE_REQUEST';
export const CELEBRITY_DELETE_SUCCESS = 'CELEBRITY_DELETE_SUCCESS';
export const CELEBRITY_DELETE_FAIL    = 'CELEBRITY_DELETE_FAIL'
export const CELEBRITY_DELETE_RESET   = 'CELEBRITY_DELETE_RESET'


// EVENT CONSTANT


export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST';
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL';

export const EVENT_USER_LIST_REQUEST = 'EVENT_USER_LIST_REQUEST';
export const EVENT_USER_LIST_SUCCESS = 'EVENT_USER_LIST_SUCCESS';
export const EVENT_USER_LIST_FAIL =    'EVENT_USER_LIST_FAIL';

export const EVENT_DETAIL_REQUEST = 'EVENT_DETAIL_REQUEST';
export const EVENT_DETAIL_SUCCESS = 'EVENT_DETAIL_SUCCESS';
export const EVENT_DETAIL_FAIL = 'EVENT_DETAIL_FAIL'


export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAIL    = 'EVENT_CREATE_FAIL'
export const EVENT_CREATE_RESET   = 'EVENT_CREATE_RESET'


export const EVENT_UPDATE_REQUEST = 'EVENT_UPDATE_REQUEST';
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS';
export const EVENT_UPDATE_FAIL    = 'EVENT_UPDATE_FAIL'
export const EVENT_UPDATE_RESET   = 'EVENT_UPDATE_RESET'


export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAIL    = 'EVENT_DELETE_FAIL'
export const EVENT_DELETE_RESET   = 'EVENT_DELETE_RESET'


// SHOP CONSTANT


export const SHOP_LIST_REQUEST =   'SHOP_LIST_REQUEST';
export const SHOP_LIST_SUCCESS =   'SHOP_LIST_SUCCESS';
export const SHOP_LIST_FAIL =      'SHOP_LIST_FAIL';

export const SHOP_USER_LIST_REQUEST =   'SHOP_USER_LIST_REQUEST';
export const SHOP_USER_LIST_SUCCESS =   'SHOP_USER_LIST_SUCCESS';
export const SHOP_USER_LIST_FAIL =      'SHOP_USER_LIST_FAIL';

export const SHOP_DETAIL_REQUEST = 'SHOP_DETAIL_REQUEST';
export const SHOP_DETAIL_SUCCESS = 'SHOP_DETAIL_SUCCESS';
export const SHOP_DETAIL_FAIL =    'SHOP_DETAIL_FAIL'

export const SHOP_CREATE_REQUEST = 'SHOP_CREATE_REQUEST';
export const SHOP_CREATE_SUCCESS = 'SHOP_CREATE_SUCCESS';
export const SHOP_CREATE_FAIL    = 'SHOP_CREATE_FAIL'
export const SHOP_CREATE_RESET   = 'SHOP_CREATE_RESET'

export const SHOP_UPDATE_REQUEST = 'SHOP_UPDATE_REQUEST';
export const SHOP_UPDATE_SUCCESS = 'SHOP_UPDATE_SUCCESS';
export const SHOP_UPDATE_FAIL    = 'SHOP_UPDATE_FAIL'
export const SHOP_UPDATE_RESET   = 'SHOP_UPDATE_RESET'

export const SHOP_DELETE_REQUEST = 'SHOP_DELETE_REQUEST';
export const SHOP_DELETE_SUCCESS = 'SHOP_DELETE_SUCCESS';
export const SHOP_DELETE_FAIL    = 'SHOP_DELETE_FAIL'
export const SHOP_DELETE_RESET   = 'SHOP_DELETE_RESET'


// HOTEL CONSTANT


export const HOTEL_LIST_REQUEST =   'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS =   'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL =      'HOTEL_LIST_FAIL'

export const HOTEL_USER_LIST_REQUEST =   'HOTEL_USER_LIST_REQUEST';
export const HOTEL_USER_LIST_SUCCESS =   'HOTEL_USER_LIST_SUCCESS';
export const HOTEL_USER_LIST_FAIL =      'HOTEL_USER_LIST_FAIL'

export const HOTEL_DETAIL_REQUEST = 'HOTEL_DETAIL_REQUEST';
export const HOTEL_DETAIL_SUCCESS = 'HOTEL_DETAIL_SUCCESS';
export const HOTEL_DETAIL_FAIL =    'HOTEL_DETAIL_FAIL'

export const HOTEL_CREATE_REQUEST = 'HOTEL_CREATE_REQUEST';
export const HOTEL_CREATE_SUCCESS = 'HOTEL_CREATE_SUCCESS';
export const HOTEL_CREATE_FAIL    = 'HOTEL_CREATE_FAIL'
export const HOTEL_CREATE_RESET   = 'HOTEL_CREATE_RESET'

export const HOTEL_UPDATE_REQUEST = 'HOTEL_UPDATE_REQUEST';
export const HOTEL_UPDATE_SUCCESS = 'HOTEL_UPDATE_SUCCESS';
export const HOTEL_UPDATE_FAIL    = 'HOTEL_UPDATE_FAIL'
export const HOTEL_UPDATE_RESET   = 'HOTEL_UPDATE_RESET'

export const HOTEL_DELETE_REQUEST = 'HOTEL_DELETE_REQUEST';
export const HOTEL_DELETE_SUCCESS = 'HOTEL_DELETE_SUCCESS';
export const HOTEL_DELETE_FAIL    = 'HOTEL_DELETE_FAIL'
export const HOTEL_DELETE_RESET   = 'HOTEL_DELETE_RESET'


// RESELLER CONSTANT


export const RESELLER_LIST_REQUEST =   'RESELLER_LIST_REQUEST';
export const RESELLER_LIST_SUCCESS =   'RESELLER_LIST_SUCCESS';
export const RESELLER_LIST_FAIL =      'RESELLER_LIST_FAIL';

export const ALL_RESELLER_LIST_REQUEST =   'ALL_RESELLER_LIST_REQUEST';
export const ALL_RESELLER_LIST_SUCCESS =   'ALL_RESELLER_LIST_SUCCESS';
export const ALL_RESELLER_LIST_FAIL =      'ALL_RESELLER_LIST_FAIL';


export const RESELLER_USER_LIST_REQUEST =   'RESELLER_USER_LIST_REQUEST';
export const RESELLER_USER_LIST_SUCCESS =   'RESELLER_USER_LIST_SUCCESS';
export const RESELLER_USER_LIST_FAIL =      'RESELLER_USER_LIST_FAIL';

export const RESELLER_DETAIL_REQUEST = 'RESELLER_DETAIL_REQUEST';
export const RESELLER_DETAIL_SUCCESS = 'RESELLER_DETAIL_SUCCESS';
export const RESELLER_DETAIL_FAIL =    'RESELLER_DETAIL_FAIL'

export const RESELLER_CREATE_REQUEST = 'RESELLER_CREATE_REQUEST';
export const RESELLER_CREATE_SUCCESS = 'RESELLER_CREATE_SUCCESS';
export const RESELLER_CREATE_FAIL    = 'RESELLER_CREATE_FAIL'
export const RESELLER_CREATE_RESET   = 'RESELLER_CREATE_RESET'

export const RESELLER_UPDATE_REQUEST = 'RESELLER_UPDATE_REQUEST';
export const RESELLER_UPDATE_SUCCESS = 'RESELLER_UPDATE_SUCCESS';
export const RESELLER_UPDATE_FAIL    = 'RESELLER_UPDATE_FAIL'
export const RESELLER_UPDATE_RESET   = 'RESELLER_UPDATE_RESET'

export const RESELLER_DELETE_REQUEST = 'RESELLER_DELETE_REQUEST';
export const RESELLER_DELETE_SUCCESS = 'RESELLER_DELETE_SUCCESS';
export const RESELLER_DELETE_FAIL    = 'RESELLER_DELETE_FAIL'
export const RESELLER_DELETE_RESET   = 'RESELLER_DELETE_RESET'


// TOUREISMS CONSTANT


export const TOURISMS_LIST_REQUEST =   'TOURISMS_LIST_REQUEST';
export const TOURISMS_LIST_SUCCESS =   'TOURISMS_LIST_SUCCESS';
export const TOURISMS_LIST_FAIL =      'TOURISMS_LIST_FAIL';

export const TOURISMS_USER_LIST_REQUEST =   'TOURISMS_USER_LIST_REQUEST';
export const TOURISMS_USER_LIST_SUCCESS =   'TOURISMS_USER_LIST_SUCCESS';
export const TOURISMS_USER_LIST_FAIL =      'TOURISMS_USER_LIST_FAIL';

export const TOURISMS_DETAIL_REQUEST = 'TOURISMS_DETAIL_REQUEST';
export const TOURISMS_DETAIL_SUCCESS = 'TOURISMS_DETAIL_SUCCESS';
export const TOURISMS_DETAIL_FAIL =    'TOURISMS_DETAIL_FAIL'

export const TOURISMS_CREATE_REQUEST = 'TOURISMS_CREATE_REQUEST';
export const TOURISMS_CREATE_SUCCESS = 'TOURISMS_CREATE_SUCCESS';
export const TOURISMS_CREATE_FAIL    = 'TOURISMS_CREATE_FAIL'
export const TOURISMS_CREATE_RESET   = 'TOURISMS_CREATE_RESET'

export const TOURISMS_UPDATE_REQUEST = 'TOURISMS_UPDATE_REQUEST';
export const TOURISMS_UPDATE_SUCCESS = 'TOURISMS_UPDATE_SUCCESS';
export const TOURISMS_UPDATE_FAIL    = 'TOURISMS_UPDATE_FAIL'
export const TOURISMS_UPDATE_RESET   = 'TOURISMS_UPDATE_RESET'

export const TOURISMS_DELETE_REQUEST = 'TOURISMS_DELETE_REQUEST';
export const TOURISMS_DELETE_SUCCESS = 'TOURISMS_DELETE_SUCCESS';
export const TOURISMS_DELETE_FAIL    = 'TOURISMS_DELETE_FAIL'
export const TOURISMS_DELETE_RESET   = 'TOURISMS_DELETE_RESET'


// JOBS CONSTANT


export const JOBS_LIST_REQUEST =   'JOBS_LIST_REQUEST';
export const JOBS_LIST_SUCCESS =   'JOBS_LIST_SUCCESS';
export const JOBS_LIST_FAIL =      'JOBS_LIST_FAIL';

export const JOBS_USER_LIST_REQUEST =   'JOBS_USER_LIST_REQUEST';
export const JOBS_USER_LIST_SUCCESS =   'JOBS_USER_LIST_SUCCESS';
export const JOBS_USER_LIST_FAIL =      'JOBS_USER_LIST_FAIL';

export const JOBS_DETAIL_REQUEST = 'JOBS_DETAIL_REQUEST';
export const JOBS_DETAIL_SUCCESS = 'JOBS_DETAIL_SUCCESS';
export const JOBS_DETAIL_FAIL =    'JOBS_DETAIL_FAIL'

export const JOBS_CREATE_REQUEST = 'JOBS_CREATE_REQUEST';
export const JOBS_CREATE_SUCCESS = 'JOBS_CREATE_SUCCESS';
export const JOBS_CREATE_FAIL    = 'JOBS_CREATE_FAIL'
export const JOBS_CREATE_RESET   = 'JOBS_CREATE_RESET'

export const JOBS_UPDATE_REQUEST = 'JOBS_UPDATE_REQUEST';
export const JOBS_UPDATE_SUCCESS = 'JOBS_UPDATE_SUCCESS';
export const JOBS_UPDATE_FAIL    = 'JOBS_UPDATE_FAIL'
export const JOBS_UPDATE_RESET   = 'JOBS_UPDATE_RESET'

export const JOBS_DELETE_REQUEST = 'JOBS_DELETE_REQUEST';
export const JOBS_DELETE_SUCCESS = 'JOBS_DELETE_SUCCESS';
export const JOBS_DELETE_FAIL    = 'JOBS_DELETE_FAIL'
export const JOBS_DELETE_RESET   = 'JOBS_DELETE_RESET'



// Meme CONSTANT


export const MEME_LIST_REQUEST =   'MEME_LIST_REQUEST';
export const MEME_LIST_SUCCESS =   'MEME_LIST_SUCCESS';
export const MEME_LIST_FAIL =      'MEME_LIST_FAIL';

export const MEME_USER_LIST_REQUEST =   'MEME_USER_LIST_REQUEST';
export const MEME_USER_LIST_SUCCESS =   'MEME_USER_LIST_SUCCESS';
export const MEME_USER_LIST_FAIL =      'MEME_USER_LIST_FAIL';

export const MEME_DETAIL_REQUEST = 'MEME_DETAIL_REQUEST';
export const MEME_DETAIL_SUCCESS = 'MEME_DETAIL_SUCCESS';
export const MEME_DETAIL_FAIL =    'MEME_DETAIL_FAIL'

export const MEME_CREATE_REQUEST = 'MEME_CREATE_REQUEST';
export const MEME_CREATE_SUCCESS = 'MEME_CREATE_SUCCESS';
export const MEME_CREATE_FAIL    = 'MEME_CREATE_FAIL'

export const MEME_CREATE_RESET   = 'MEME_CREATE_RESET'
export const MEME_UPDATE_REQUEST = 'MEME_UPDATE_REQUEST';
export const MEME_UPDATE_SUCCESS = 'MEME_UPDATE_SUCCESS';
export const MEME_UPDATE_FAIL    = 'MEME_UPDATE_FAIL'
export const MEME_UPDATE_RESET   = 'MEME_UPDATE_RESET'

export const MEME_DELETE_REQUEST = 'MEME_DELETE_REQUEST';
export const MEME_DELETE_SUCCESS = 'MEME_DELETE_SUCCESS';
export const MEME_DELETE_FAIL    = 'MEME_DELETE_FAIL'
export const MEME_DELETE_RESET   = 'MEME_DELETE_RESET'

// LOCAL CONSTANT


export const LOCAL_LIST_REQUEST =   'LOCAL_LIST_REQUEST';
export const LOCAL_LIST_SUCCESS =   'LOCAL_LIST_SUCCESS';
export const LOCAL_LIST_FAIL =      'LOCAL_LIST_FAIL';

export const LOCAL_USER_LIST_REQUEST =   'LOCAL_USER_LIST_REQUEST';
export const LOCAL_USER_LIST_SUCCESS =   'LOCAL_USER_LIST_SUCCESS';
export const LOCAL_USER_LIST_FAIL =      'LOCAL_USER_LIST_FAIL';

export const LOCAL_DETAIL_REQUEST = 'LOCAL_DETAIL_REQUEST';
export const LOCAL_DETAIL_SUCCESS = 'LOCAL_DETAIL_SUCCESS';
export const LOCAL_DETAIL_FAIL =    'LOCAL_DETAIL_FAIL';

export const LOCAL_CREATE_REQUEST = 'LOCAL_CREATE_REQUEST';
export const LOCAL_CREATE_SUCCESS = 'LOCAL_CREATE_SUCCESS';
export const LOCAL_CREATE_FAIL    = 'LOCAL_CREATE_FAIL'
export const LOCAL_CREATE_RESET   = 'LOCAL_CREATE_RESET';

export const LOCAL_UPDATE_REQUEST = 'LOCAL_UPDATE_REQUEST';
export const LOCAL_UPDATE_SUCCESS = 'LOCAL_UPDATE_SUCCESS';
export const LOCAL_UPDATE_FAIL    = 'LOCAL_UPDATE_FAIL'
export const LOCAL_UPDATE_RESET   = 'LOCAL_UPDATE_RESET';

export const LOCAL_DELETE_REQUEST = 'LOCAL_DELETE_REQUEST';
export const LOCAL_DELETE_SUCCESS = 'LOCAL_DELETE_SUCCESS';
export const LOCAL_DELETE_FAIL    = 'LOCAL_DELETE_FAIL'
export const LOCAL_DELETE_RESET   = 'LOCAL_DELETE_RESET'

// REQUEST FORM CONSTANT


export const FORM_LIST_REQUEST =   'FORM_LIST_REQUEST';
export const FORM_LIST_SUCCESS =   'FORM_LIST_SUCCESS';
export const FORM_LIST_FAIL =      'FORM_LIST_FAIL'

export const FORM_DETAIL_REQUEST = 'FORM_DETAIL_REQUEST';
export const FORM_DETAIL_SUCCESS = 'FORM_DETAIL_SUCCESS';
export const FORM_DETAIL_FAIL =    'FORM_DETAIL_FAIL'

export const FORM_CREATE_REQUEST = 'FORM_CREATE_REQUEST';
export const FORM_CREATE_SUCCESS = 'FORM_CREATE_SUCCESS';
export const FORM_CREATE_FAIL    = 'FORM_CREATE_FAIL'

export const FORM_CREATE_RESET   = 'FORM_CREATE_RESET'
export const FORM_UPDATE_REQUEST = 'FORM_UPDATE_REQUEST';
export const FORM_UPDATE_SUCCESS = 'FORM_UPDATE_SUCCESS';
export const FORM_UPDATE_FAIL    = 'FORM_UPDATE_FAIL'
export const FORM_UPDATE_RESET   = 'FORM_UPDATE_RESET'

//bANNER CONSTANT


export const BANNER_LIST_REQUEST =   'BANNER_LIST_REQUEST';
export const BANNER_LIST_SUCCESS =   'BANNER_LIST_SUCCESS';
export const BANNER_LIST_FAIL =      'BANNER_LIST_FAIL'


