export const TECH_LIST_REQUEST = 'TECH_LIST_REQUEST'
export const TECH_LIST_SUCCESS = 'TECH_LIST_SUCCESS'
export const TECH_LIST_FAIL = 'TECH_LIST_FAIL'

export const HEALTH_LIST_REQUEST = 'HEALTH_LIST_REQUEST'
export const HEALTH_LIST_SUCCESS = 'HEALTH_LIST_SUCCESS'
export const HEALTH_LIST_FAIL =    'HEALTH_LIST_FAIL'

export const BUSINESS_LIST_REQUEST = 'BUSINESS_LIST_REQUEST'
export const BUSINESS_LIST_SUCCESS = 'BUSINESS_LIST_SUCCESS'
export const BUSINESS_LIST_FAIL =    'BUSINESS_LIST_FAIL'

export const SCIENCE_LIST_REQUEST = 'SCIENCE_LIST_REQUEST'
export const SCIENCE_LIST_SUCCESS = 'SCIENCE_LIST_SUCCESS'
export const SCIENCE_LIST_FAIL =    'SCIENCE_LIST_FAIL'

export const TECH_DETAIL_REQUEST = 'TECH_DETAIL_REQUEST'
export const TECH_DETAIL_SUCCESS = 'TECH_DETAIL_SUCCESS'
export const TECH_DETAIL_FAIL =    'TECH_DETAIL_FAIL'

export const BUSINESS_DETAIL_REQUEST = 'BUSINESS_DETAIL_REQUEST'
export const BUSINESS_DETAIL_SUCCESS = 'BUSINESS_DETAIL_SUCCESS'
export const BUSINESS_DETAIL_FAIL =    'BUSINESS_DETAIL_FAIL'

export const SCIENCE_DETAIL_REQUEST = 'SCIENCE_DETAIL_REQUEST'
export const SCIENCE_DETAIL_SUCCESS = 'SCIENCE_DETAIL_SUCCESS'
export const SCIENCE_DETAIL_FAIL =    'SCIENCE_DETAIL_FAIL'

export const CREATE_TECH_REQUEST  = 'CREATE_TECH_REQUEST'
export const CREATE_TECH_SUCCESS = 'CREATE_TECH_SUCCESS'
export const CREATE_TECH_FAIL = 'CREATE_TECH_FAIL'

export const CREATE_HEALTH_REQUEST  = 'CREATE_HEALTH_REQUEST'
export const CREATE_HEALTH_SUCCESS = 'CREATE_HEALTH_SUCCESS'
export const CREATE_HEALTH_FAIL = 'CREATE_HEALTH_FAIL'

export const CREATE_BUSINESS_REQUEST  = 'CREATE_BUSINESS_REQUEST'
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS'
export const CREATE_BUSINESS_FAIL = 'CREATE_BUSINESS_FAIL'

export const CREATE_SCIENCE_REQUEST  = 'CREATE_SCIENCE_REQUEST'
export const CREATE_SCIENCE_SUCCESS = 'CREATE_SCIENCE_SUCCESS'
export const CREATE_SCIENCE_FAIL = 'CREATE_SCIENCE_FAIL'
